# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------
#export ISENSE_PATH=/home/amaxilatis/Applications/SDK/iSense_full
#export ISENSE_PATH=/home/amaxilatis/sdks/iSenseAll
export ISENSE_PATH=/home/amaxilatis/sdks/isense-tbaum/

all: clean isense
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=general_tests.cpp
export BIN_OUT=general_tests

include ../Makefile
