# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

export ISENSE_PATH=/home/amaxilatis/sdks/Collector

all: shawn
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
#all: contiki_inga
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=hvac_app.cpp
export BIN_OUT=hvac_app

#export ADD_CXXFLAGS="-DWISELIB_ALLOW_SLEEP=1 -DWISELIB_ALLOW_DOZE=1"

include ../Makefile
