# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------
#export ISENSE_PATH=/home/amaxilatis/Applications/SDK/iSense_full
export ISENSE_PATH=/home/amaxilatis/sdks/iSenseAll

all: clean isense
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=storage_test.cpp
export BIN_OUT=storage_test

include ../Makefile
