# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------

#export ISENSE_PATH=/home/amaxilatis/sdks/iSense_typical/
export ISENSE_PATH=/home/amaxilatis/sdks/isense-tbaum
#export ISENSE_PATH=/home/amaxilatis/sdks/isense_typical/


all: clean isense
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=clustering_app.cpp
export BIN_OUT=clustering_app

include ../Makefile
