# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------


all: clean isense
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

export APP_SRC=clustering_app.cpp
export BIN_OUT=clustering_app

include ../Makefile
