# ----------------------------------------
# Environment variable WISELIB_PATH needed
# ----------------------------------------
#export ISENSE_PATH=/home/amaxilatis/Applications/SDK/iSense_full
#export ISENSE_PATH=/home/amaxilatis/sdks/iSense

all: clean isense
# all: scw_msb
# all: contiki_msb
# all: contiki_micaz
# all: isense
# all: tinyos-tossim
# all: tinyos-micaz

#export APP_SRC=clustering_sema_app_tuplestore.cpp
export APP_SRC=clustering_sema_app.cpp
export BIN_OUT=clustering_sema_app

include ../Makefile
